const express = require('express');
const mongoose = require('mongoose');
const { body, query, validationResult } = require('express-validator');
const Parcel = require('../models/Parcel');
const Application = require('../models/Application');
const Payment = require('../models/Payment');
const FeeSettings = require('../models/FeeSettings');
const { requireAuth, requireRole, requirePhoneVerified, requireIdVerified } = require('../middleware/auth');
const { generateReference } = require('../utils/reference');
const { countyCentroid, distanceKm } = require('../utils/geo');
const cache = require('../middleware/cache');
const { MAX_APPLICANTS } = require('../utils/constants');

const router = express.Router();

const TAGS_ALLOWED = ['Financing', 'Insured', 'River access', 'Road access', 'Borehole', 'Export zone'];
const LIST_TTL_MS = 30 * 1000; // marketplace list/match results change as fast as listings do
const DETAIL_TTL_MS = 60 * 1000; // a single parcel page is read far more than it's edited

// Listings don't get pulled the moment someone applies — accepting is what takes a
// parcel off the market (see routes/admin.js). Instead the marketplace card and
// listing page show how many people have applied, to create urgency without ever
// hiding a parcel that's still actually open. This attaches an `applicantCount` and
// `spotsRemaining` (out of MAX_APPLICANTS) to each parcel in a list.
// Strips the full GIS productivity report down to a light, non-sensitive preview
// (score + generation date) wherever a parcel is returned from a cached, shared
// endpoint (the marketplace list, Landora Match results, or a single parcel's
// detail page) — see GET /:idOrSlug/productivity-report for the per-user, paywalled
// full version.
function redactReport(parcel) {
  const fullReport = parcel.productivityReport;
  return {
    ...parcel,
    hasProductivityReport: Boolean(fullReport && fullReport.generatedAt),
    productivityReport: fullReport
      ? { scoreLabel: fullReport.scoreLabel, generatedAt: fullReport.generatedAt }
      : undefined,
  };
}

async function withApplicantCounts(parcels) {
  const ids = parcels.map((p) => p._id);
  if (ids.length === 0) return parcels;
  const counts = await Application.aggregate([
    { $match: { parcel: { $in: ids }, type: 'lease', status: { $ne: 'withdrawn' } } },
    { $group: { _id: '$parcel', count: { $sum: 1 } } },
  ]);
  const countMap = Object.fromEntries(counts.map((c) => [c._id.toString(), c.count]));
  return parcels.map((p) => {
    const applicantCount = countMap[p._id.toString()] || 0;
    const maxApplicants = p.maxApplicants || MAX_APPLICANTS;
    return redactReport({
      ...p,
      applicantCount,
      maxApplicants,
      spotsRemaining: Math.max(0, maxApplicants - applicantCount),
    });
  });
}

// A listing's leaseDeadline is a planting season cutoff, not a hard delete — once it
// passes we lazily flip status from "available" to "unlisted" the next time anyone
// reads the marketplace, rather than running a cron job. The parcel stays fully
// intact (and still pre bookable, see preBookingEnabled) for the next season.
async function expireDeadlines() {
  await Parcel.updateMany(
    { status: 'available', leaseDeadline: { $ne: null, $lt: new Date() } },
    { $set: { status: 'unlisted' } }
  );
}

function isObjectId(value) {
  return mongoose.Types.ObjectId.isValid(value) && String(new mongoose.Types.ObjectId(value)) === String(value);
}

// Land productivity report access — the report is generated by the internal GIS
// engine for every parcel, but a farmer/buyer must pay to unlock the full report
// (see FeeSettings.gisReport and the 'gis_report' Payment type). The listing's own
// owner and admins always see it for free.
async function hasGisReportAccess(parcelId, userId) {
  if (!userId) return false;
  const payment = await Payment.findOne({
    parcel: parcelId,
    user: userId,
    type: 'gis_report',
    status: 'success',
  }).lean();
  return !!payment;
}

// Strips the full productivityReport out of a parcel payload and replaces it with a
// non-sensitive preview (score + when it was generated) plus a `locked` flag and
// the current price to unlock it. Used on every public/listable parcel response —
// GET /:idOrSlug is cached (middleware/cache.js) and NOT keyed per-user, so the
// full report must never be included there; only the dedicated, per-user
// GET /:id/productivity-report endpoint below (which bypasses the cache and checks
// access per request) ever returns it in full.
function redactProductivityReport(parcel, gisReportPrice) {
  if (!parcel.productivityReport) return parcel;
  const { scoreLabel, generatedAt } = parcel.productivityReport;
  return {
    ...parcel,
    productivityReport: undefined,
    productivityReportPreview: { scoreLabel: scoreLabel || parcel.score, generatedAt },
    productivityReportLocked: true,
    gisReportPriceKes: gisReportPrice,
  };
}

// Public: browse/search/filter listings, including the Landora Match engine filters
// (near/within, land use, acreage band, budget ceiling, water access). Only ever
// returns real, landowner-created parcels.
// Scores a parcel against a set of Landora Match requirements (0-100) and returns why
// it scored that way, so the marketplace can present Match as a real recommender —
// ranked results with a percentage and plain-language reasons — rather than a filter
// that just hides everything that doesn't match exactly.
function scoreMatch(parcel, criteria) {
  const { crop, minSize, maxSize, maxPrice, waterAccess, origin, radiusKm } = criteria;
  const parts = []; // { weight, score, reason }

  if (crop) {
    const isMatch = String(parcel.crop || '').trim().toLowerCase() === String(crop).trim().toLowerCase();
    parts.push({
      weight: 25,
      score: isMatch ? 100 : 35,
      reason: isMatch ? `Matches your land use (${crop})` : `Listed for ${parcel.crop}, not ${crop}`,
      positive: isMatch,
    });
  }

  if (maxPrice) {
    const price = parcel.pricePerAcrePerSeason;
    const max = parseFloat(maxPrice);
    let priceScore;
    if (price <= max) {
      priceScore = 100;
    } else {
      const overBy = (price - max) / max;
      priceScore = Math.max(0, Math.round(100 - overBy * 150));
    }
    parts.push({
      weight: 25,
      score: priceScore,
      reason: price <= max ? 'Within your budget' : priceScore > 40 ? 'Slightly above your budget' : 'Over your budget',
      positive: priceScore >= 60,
    });
  }

  if (minSize || maxSize) {
    const min = minSize ? parseFloat(minSize) : null;
    const max = maxSize ? parseFloat(maxSize) : null;
    const size = parcel.sizeAcres;
    let sizeScore;
    if ((min == null || size >= min) && (max == null || size <= max)) {
      sizeScore = 100;
    } else {
      const bound = size < (min ?? size) ? min : max;
      const span = Math.max(bound, 1);
      sizeScore = Math.max(0, Math.round(100 - (Math.abs(size - bound) / span) * 100));
    }
    parts.push({
      weight: 20,
      score: sizeScore,
      reason: sizeScore === 100 ? 'Right size for your acreage range' : 'Slightly outside your acreage range',
      positive: sizeScore >= 60,
    });
  }

  if (origin && radiusKm) {
    const centroid = parcel.mapData && parcel.mapData.centroidLat != null
      ? { lat: parcel.mapData.centroidLat, lng: parcel.mapData.centroidLng }
      : null;
    if (centroid) {
      const d = distanceKm(origin, centroid);
      let distScore;
      if (d <= radiusKm) {
        distScore = 100;
      } else {
        distScore = Math.max(0, Math.round(100 - ((d - radiusKm) / radiusKm) * 100));
      }
      parts.push({
        weight: 20,
        score: distScore,
        reason: d <= radiusKm ? `${d.toFixed(1)}km away, within your radius` : `${d.toFixed(1)}km away, just outside your radius`,
        positive: distScore >= 60,
      });
    } else {
      parts.push({
        weight: 20,
        score: 55,
        reason: 'Distance not yet confirmed by the GIS engine',
        positive: false,
      });
    }
  }

  if (waterAccess === 'true') {
    parts.push({
      weight: 10,
      score: parcel.waterAccess ? 100 : 0,
      reason: parcel.waterAccess ? 'Has water access' : 'No confirmed water access',
      positive: !!parcel.waterAccess,
    });
  }

  // A small always-on bonus for the GIS plot rating, so a strong parcel edges out an
  // otherwise-identical one even when every explicit requirement ties.
  const gradeScores = { 'A+': 100, A: 92, 'A-': 85, 'B+': 75, B: 65, 'B-': 55, 'C+': 45, C: 35 };
  const gradeScore = parcel.score && gradeScores[parcel.score] != null ? gradeScores[parcel.score] : 50;
  parts.push({
    weight: 10,
    score: gradeScore,
    reason: gradeScore >= 85 ? `Strong GIS plot rating (${parcel.score})` : null,
    positive: gradeScore >= 85,
  });

  const totalWeight = parts.reduce((sum, p) => sum + p.weight, 0);
  const weightedScore = parts.reduce((sum, p) => sum + p.weight * p.score, 0) / totalWeight;

  const reasons = parts
    .filter((p) => p.positive && p.reason)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map((p) => p.reason);

  return { matchScore: Math.round(weightedScore), matchReasons: reasons };
}

router.get(
  '/',
  [
    query('county').optional().trim(),
    query('crop').optional().trim(),
    query('minSize').optional().isFloat({ min: 0 }),
    query('maxSize').optional().isFloat({ min: 0 }),
    query('maxPrice').optional().isFloat({ min: 0 }),
    query('financingAvailable').optional().isBoolean(),
    query('insured').optional().isBoolean(),
    query('waterAccess').optional().isBoolean(),
    query('minScore').optional().trim(),
    query('near').optional().trim(),
    query('withinKm').optional().isFloat({ min: 0 }),
    query('match').optional().isBoolean(),
    query('search').optional().trim(),
    query('page').optional().isInt({ min: 1 }),
    query('limit').optional().isInt({ min: 1, max: 50 }),
  ],
  cache.cacheGet(LIST_TTL_MS),
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ error: 'Invalid filter parameters' });
    }

    const {
      county, crop, minSize, maxSize, maxPrice, financingAvailable, insured, waterAccess,
      minScore, near, withinKm, search, match,
    } = req.query;
    const page = parseInt(req.query.page, 10) || 1;
    const limit = parseInt(req.query.limit, 10) || 12;
    const isMatchMode = match === 'true';

    await expireDeadlines();

    const filter = { status: 'available' };
    if (minScore) filter.score = minScore;
    if (search) filter.$text = { $search: search };

    if (isMatchMode) {
      // Landora Match acts as a recommender: don't hard-exclude parcels that are
      // merely an imperfect fit — rank everything available by how well it scores
      // against what was asked for instead. Only the criteria the person actually
      // filled in are weighed, so the ranking is genuinely dynamic per submission
      // rather than a fixed formula everyone gets the same result from.
      const origin = near ? countyCentroid(near) : null;
      const radiusKm = withinKm ? parseFloat(withinKm) : null;

      const parcels = await Parcel.find(filter).populate('owner', 'name county profilePicture').lean();
      const withCounts = await withApplicantCounts(parcels);
      const ranked = withCounts
        .map((plain) => {
          const { matchScore, matchReasons } = scoreMatch(plain, {
            crop, minSize, maxSize, maxPrice, waterAccess, origin, radiusKm,
          });
          return { ...plain, matchScore, matchReasons };
        })
        .sort((a, b) => b.matchScore - a.matchScore);

      const total = ranked.length;
      const start = (page - 1) * limit;
      const pageItems = ranked.slice(start, start + limit);
      return res.json({ parcels: pageItems, total, page, pages: Math.ceil(total / limit) || 1, matchMode: true });
    }

    if (county && county !== 'All counties') filter.county = county;
    if (crop && crop !== 'Any crop' && crop !== 'Any agricultural use') filter.crop = crop;
    if (financingAvailable === 'true') filter.financingAvailable = true;
    if (insured === 'true') filter.insured = true;
    if (waterAccess === 'true') filter.waterAccess = true;
    if (minSize || maxSize) {
      filter.sizeAcres = {};
      if (minSize) filter.sizeAcres.$gte = parseFloat(minSize);
      if (maxSize) filter.sizeAcres.$lte = parseFloat(maxSize);
    }
    if (maxPrice) filter.pricePerAcrePerSeason = { $lte: parseFloat(maxPrice) };

    // "Near / within" from the plain marketplace filters: prefer a real distance
    // check against the parcel's GIS centroid when we have one, otherwise fall back
    // to a county match.
    const origin = near ? countyCentroid(near) : null;
    const radiusKm = withinKm ? parseFloat(withinKm) : null;

    let [parcels, total] = await Promise.all([
      Parcel.find(filter)
        .sort({ createdAt: -1 })
        .populate('owner', 'name county profilePicture')
        .lean(),
      Parcel.countDocuments(filter),
    ]);

    if (origin && radiusKm) {
      parcels = parcels.filter((p) => {
        const centroid = p.mapData && p.mapData.centroidLat != null
          ? { lat: p.mapData.centroidLat, lng: p.mapData.centroidLng }
          : null;
        if (centroid) {
          const d = distanceKm(origin, centroid);
          return d != null && d <= radiusKm;
        }
        return p.county === near;
      });
      total = parcels.length;
    }

    const start = (page - 1) * limit;
    const pageItems = await withApplicantCounts(parcels.slice(start, start + limit));

    res.json({ parcels: pageItems, total, page, pages: Math.ceil(total / limit) || 1 });
  }
);

// Suggests a fair lease rate range for a landowner who is still setting their price,
// based on what similar parcels (same crop, then same county, then the whole
// marketplace as a fallback) are actually listed at right now — a small, real
// recommender rather than a fixed lookup table.
router.get(
  '/pricing-suggestion',
  [
    query('county').optional().trim(),
    query('crop').optional().trim(),
    query('sizeAcres').optional().isFloat({ min: 0 }),
    query('waterAccess').optional().isBoolean(),
    query('financingAvailable').optional().isBoolean(),
  ],
  async (req, res) => {
    const { county, crop, waterAccess, financingAvailable } = req.query;

    async function pricesFor(filter) {
      const rows = await Parcel.find(filter).select('pricePerAcrePerSeason').limit(200).lean();
      return rows.map((r) => r.pricePerAcrePerSeason).filter((n) => typeof n === 'number' && n > 0);
    }

    let prices = [];
    let basis = 'marketplace-wide';
    if (county && crop) {
      prices = await pricesFor({ county, crop });
      if (prices.length >= 3) basis = 'same county and land use';
    }
    if (prices.length < 3 && crop) {
      prices = await pricesFor({ crop });
      if (prices.length >= 3) basis = 'same land use, all counties';
    }
    if (prices.length < 3 && county) {
      prices = await pricesFor({ county });
      if (prices.length >= 3) basis = 'same county, all land uses';
    }
    if (prices.length < 3) {
      prices = await pricesFor({});
      basis = 'marketplace-wide';
    }

    if (prices.length === 0) {
      return res.json({
        available: false,
        message: 'Not enough listings yet to suggest a rate. Price competitively against nearby land for now.',
      });
    }

    prices.sort((a, b) => a - b);
    const mid = Math.floor(prices.length / 2);
    const median = prices.length % 2 === 0 ? (prices[mid - 1] + prices[mid]) / 2 : prices[mid];

    // Modest adjustments for factors that reliably move a fair rate: on site water
    // access and offering financing both make a parcel more attractive, so they
    // support a slightly higher ask.
    let adjustment = 1;
    if (waterAccess === 'true') adjustment += 0.06;
    if (financingAvailable === 'true') adjustment += 0.03;

    const suggestedMin = Math.round((median * 0.88 * adjustment) / 50) * 50;
    const suggestedMax = Math.round((median * 1.15 * adjustment) / 50) * 50;

    res.json({
      available: true,
      basis,
      sampleSize: prices.length,
      median: Math.round(median),
      suggestedMin,
      suggestedMax,
    });
  }
);

// Public: single parcel detail. Accepts either the Mongo id or the readable slug, so
// every link keeps working, and returns 404 (not a crash) when neither resolves.
// The full GIS land productivity report is intentionally NOT included here — this
// response is cached and shared across every visitor (see cache.cacheGet above), so
// it can never vary per-user. A light, non-sensitive preview (score + generation
// date) is included instead; the full report is fetched separately, per-user, via
// GET /:idOrSlug/productivity-report below, which checks payment/ownership on every
// call and is never cached.
router.get('/:idOrSlug', cache.cacheGet(DETAIL_TTL_MS), async (req, res) => {
  await expireDeadlines();
  const { idOrSlug } = req.params;
  const lookup = isObjectId(idOrSlug) ? { _id: idOrSlug } : { slug: idOrSlug };
  const parcel = await Parcel.findOne(lookup).populate('owner', 'name county phone profilePicture').lean();
  if (!parcel) return res.status(404).json({ error: 'Parcel not found' });
  const [withCount] = await withApplicantCounts([parcel]);
  res.json({ parcel: withCount });
});

// Buyer/owner/admin: fetch the full GIS land productivity report for one parcel.
// The landowner who owns the parcel and any admin always get it for free; anyone
// else (a prospective tenant farmer) needs a successful 'gis_report' payment for
// this exact parcel — see routes/payments.js resolveAmount('gis_report'). Never
// cached, since access is per-user.
router.get('/:idOrSlug/productivity-report', requireAuth, async (req, res) => {
  const { idOrSlug } = req.params;
  const lookup = isObjectId(idOrSlug) ? { _id: idOrSlug } : { slug: idOrSlug };
  const parcel = await Parcel.findOne(lookup);
  if (!parcel) return res.status(404).json({ error: 'Parcel not found' });

  const fees = await FeeSettings.getSingleton();
  const price = fees.gisReport.priceKes;

  if (!parcel.productivityReport || !parcel.productivityReport.generatedAt) {
    return res.json({ unlocked: false, hasReport: false, price, productivityReport: null });
  }

  const isOwner = String(parcel.owner) === String(req.user._id);
  const isAdmin = req.user.role === 'admin';
  let unlocked = isOwner || isAdmin;

  if (!unlocked) {
    const paid = await Payment.findOne({
      user: req.user._id,
      parcel: parcel._id,
      type: 'gis_report',
      status: 'success',
    }).lean();
    unlocked = Boolean(paid);
  }

  if (!unlocked) {
    return res.json({ unlocked: false, hasReport: true, price, productivityReport: null });
  }

  res.json({ unlocked: true, hasReport: true, price, productivityReport: parcel.productivityReport });
});

// Landowner: create a listing. This is the "part one" submission — key facts, the
// productivity report, the GIS map, and the video walkthrough are added afterwards by
// the internal GIS-engine/admin review pass (see routes/admin.js).
router.post(
  '/',
  requireAuth,
  requireRole('landowner'),
  // Sellers must have a verified phone number and a verified national ID before
  // they can publish a listing — see requirePhoneVerified / requireIdVerified in
  // middleware/auth.js.
  requirePhoneVerified,
  requireIdVerified,
  [
    body('title').trim().isLength({ min: 3, max: 140 }),
    body('county').trim().notEmpty(),
    body('location').trim().notEmpty(),
    body('sizeAcres').isFloat({ min: 0.1 }),
    body('totalAcres').optional({ checkFalsy: true }).isFloat({ min: 0.1 }),
    body('pricePerAcrePerSeason').isFloat({ min: 0 }),
    body('crop').trim().notEmpty(),
    body('season').optional({ checkFalsy: true }).trim(),
    body('reference').optional({ checkFalsy: true }).trim(),
    body('description').optional({ checkFalsy: true }).trim().isLength({ max: 4000 }),
    body('tags').optional().isArray(),
    body('photos').optional().isArray({ max: 50 }),
    body('financingAvailable').optional().isBoolean(),
    body('insured').optional().isBoolean(),
    body('waterAccess').optional().isBoolean(),
    body('leaseDeadline').optional({ checkFalsy: true }).isISO8601(),
    body('preBookingEnabled').optional().isBoolean(),
  ],
  async (req, res) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({ error: errors.array()[0].msg, details: errors.array() });
    }

    const {
      title, county, location, sizeAcres, totalAcres, pricePerAcrePerSeason, crop, season,
      reference, description, tags, photos, financingAvailable, insured, waterAccess,
      leaseDeadline, preBookingEnabled,
    } = req.body;

    const cleanTags = Array.isArray(tags) ? tags.filter((t) => TAGS_ALLOWED.includes(t)) : [];

    const parcel = await Parcel.create({
      owner: req.user._id,
      title, county, location, sizeAcres,
      totalAcres: totalAcres || sizeAcres,
      pricePerAcrePerSeason, crop, season,
      reference: reference || generateReference(county, location),
      description,
      tags: cleanTags,
      photos: Array.isArray(photos) ? photos.slice(0, 50) : [],
      financingAvailable: !!financingAvailable,
      insured: !!insured,
      waterAccess: !!waterAccess,
      leaseDeadline: leaseDeadline || null,
      preBookingEnabled: preBookingEnabled !== false,
      enrichmentStatus: 'pending',
    });

    res.status(201).json({ parcel });
    cache.invalidate('/api/parcels');
  }
);

// Landowner: list my own parcels (any status), with application counts.
router.get('/mine/list', requireAuth, requireRole('landowner'), async (req, res) => {
  const parcels = await Parcel.find({ owner: req.user._id }).sort({ createdAt: -1 }).lean();
  const counts = await Application.aggregate([
    { $match: { landowner: req.user._id } },
    { $group: { _id: '$parcel', count: { $sum: 1 } } },
  ]);
  const countMap = Object.fromEntries(counts.map((c) => [c._id.toString(), c.count]));
  res.json({
    parcels: parcels.map((p) => ({ ...p, applicationCount: countMap[p._id.toString()] || 0 })),
  });
});

// Landowner: update own parcel (status, pricing, details). Landowners can edit their
// own listing's base fields, but not the internally-verified key facts / productivity
// report / map / video — those are admin-only (see routes/admin.js).
router.patch('/:id', requireAuth, requireRole('landowner'), async (req, res) => {
  const parcel = await Parcel.findById(req.params.id);
  if (!parcel) return res.status(404).json({ error: 'Parcel not found' });
  if (parcel.owner.toString() !== req.user._id.toString()) {
    return res.status(403).json({ error: 'You do not own this parcel' });
  }

  const editable = [
    'title', 'county', 'location', 'sizeAcres', 'totalAcres', 'pricePerAcrePerSeason', 'crop', 'season',
    'reference', 'description', 'tags', 'photos', 'financingAvailable', 'insured', 'waterAccess', 'status',
    'leaseDeadline', 'preBookingEnabled',
  ];
  editable.forEach((field) => {
    if (req.body[field] !== undefined) parcel[field] = req.body[field];
  });
  if (Array.isArray(parcel.photos) && parcel.photos.length > 50) {
    parcel.photos = parcel.photos.slice(0, 50);
  }

  await parcel.save();
  res.json({ parcel });
  cache.invalidate('/api/parcels');
});

// Landowner: delete own parcel.
router.delete('/:id', requireAuth, requireRole('landowner'), async (req, res) => {
  const parcel = await Parcel.findById(req.params.id);
  if (!parcel) return res.status(404).json({ error: 'Parcel not found' });
  if (parcel.owner.toString() !== req.user._id.toString()) {
    return res.status(403).json({ error: 'You do not own this parcel' });
  }
  await parcel.deleteOne();
  res.json({ ok: true });
  cache.invalidate('/api/parcels');
});

module.exports = router;
