const mongoose = require('mongoose');

// Rich land productivity report + parcel-level GIS map, generated by the automated
// GIS/actuarial engine and reviewed by the Landora field team. This is the same
// "second part" data described in the key facts panel and productivity report on the
// listing page — it is added/edited internally (admin) after the landowner submits
// the base listing.
const productivityReportSchema = new mongoose.Schema(
  {
    scoreLabel: { type: String, trim: true, maxlength: 4 }, // e.g. "A", "A-", "B+"
    rateRangeMin: Number,
    rateRangeMax: Number,
    metrics: {
      soilQuality: { type: Number, min: 0, max: 100 },
      rainfallReliability: { type: Number, min: 0, max: 100 },
      marketAccess: { type: Number, min: 0, max: 100 },
      historicalYield: { type: Number, min: 0, max: 100 },
    },
    soilClassification: { type: String, trim: true, maxlength: 80 },
    soilNote: { type: String, trim: true, maxlength: 300 },
    avgSeasonalRainfall: { type: String, trim: true, maxlength: 80 },
    rainfallNote: { type: String, trim: true, maxlength: 300 },
    vegetationHealth: { type: String, trim: true, maxlength: 80 },
    vegetationNote: { type: String, trim: true, maxlength: 300 },
    elevationTerrain: { type: String, trim: true, maxlength: 80 },
    terrainNote: { type: String, trim: true, maxlength: 300 },
    marketAccessSummary: { type: String, trim: true, maxlength: 80 },
    marketAccessNote: { type: String, trim: true, maxlength: 300 },
    demandSignal: { type: String, trim: true, maxlength: 80 },
    demandNote: { type: String, trim: true, maxlength: 300 },
    comparableParcels: { type: String, trim: true, maxlength: 80 },
    comparableNote: { type: String, trim: true, maxlength: 300 },
    previousCropRotation: { type: String, trim: true, maxlength: 120 },
    cropRotationNote: { type: String, trim: true, maxlength: 300 },
    waterAccessSummary: { type: String, trim: true, maxlength: 80 },
    waterAccessNote: { type: String, trim: true, maxlength: 300 },
    rainfallHistory: [
      {
        season: { type: String, trim: true, maxlength: 20 },
        insurable: { type: Boolean, default: true },
      },
    ],
    rainfallHistoryNote: { type: String, trim: true, maxlength: 300 },
    agronomicNotes: { type: String, trim: true, maxlength: 2000 },
    generatedAt: Date,
  },
  { _id: false }
);

const mapDataSchema = new mongoose.Schema(
  {
    centroidLat: Number,
    centroidLng: Number,
    boundaryPoints: [{ lat: Number, lng: Number, _id: false }],
    streamPoints: [{ lat: Number, lng: Number, _id: false }],
    roadPoints: [{ lat: Number, lng: Number, _id: false }],
    sourceNote: {
      type: String,
      trim: true,
      maxlength: 300,
      default:
        'Boundary derived from OpenStreetMap and county cadastral records, refined against Sentinel-2 satellite imagery.',
    },
  },
  { _id: false }
);

const keyFactsSchema = new mongoose.Schema(
  {
    acreageTotal: Number,
    suggestedCrop: { type: String, trim: true, maxlength: 80 },
    waterAccessDetail: { type: String, trim: true, maxlength: 200 },
    tenure: { type: String, trim: true, maxlength: 120 },
    financingDetail: { type: String, trim: true, maxlength: 200 },
    insuranceDetail: { type: String, trim: true, maxlength: 200 },
  },
  { _id: false }
);

// Landowner identity and land title verification. Every listing is expected to be
// checked against the Ministry of Lands' Ardhisasa portal; when a parcel/title isn't
// yet reachable there, an admin falls back to a manual search (county registry, a
// physical search at the lands office, etc.) and records what was found here. This is
// distinct from the descriptive GIS key facts above.
const titleVerificationSchema = new mongoose.Schema(
  {
    status: {
      type: String,
      enum: ['unverified', 'pending', 'verified', 'flagged'],
      default: 'unverified',
    },
    method: { type: String, enum: ['ardhisasa', 'manual'], default: 'ardhisasa' },
    titleNumber: { type: String, trim: true, maxlength: 80 },
    landownerNameOnTitle: { type: String, trim: true, maxlength: 120 },
    encumbrances: { type: String, trim: true, maxlength: 200, default: 'None' },
    disbursementRecordLabel: { type: String, trim: true, maxlength: 120 },
    notes: { type: String, trim: true, maxlength: 500 },
    checkedBy: { type: String, trim: true, maxlength: 120 },
    checkedAt: Date,
  },
  { _id: false }
);

const videoWalkthroughSchema = new mongoose.Schema(
  {
    url: { type: String, trim: true, maxlength: 500 },
    caption: { type: String, trim: true, maxlength: 200 },
    durationLabel: { type: String, trim: true, maxlength: 10 },
    addedAt: Date,
  },
  { _id: false }
);

const parcelSchema = new mongoose.Schema(
  {
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 140 },
    reference: { type: String, trim: true, maxlength: 60, unique: true, sparse: true },
    county: { type: String, required: true, trim: true, maxlength: 60, index: true },
    location: { type: String, required: true, trim: true, maxlength: 140 },
    sizeAcres: { type: Number, required: true, min: 0.1 },
    totalAcres: { type: Number, min: 0.1 },
    pricePerAcrePerSeason: { type: Number, required: true, min: 0 },
    crop: { type: String, required: true, trim: true, maxlength: 60, index: true },
    season: { type: String, trim: true, maxlength: 40 },
    tags: [{ type: String, trim: true, maxlength: 40 }],
    description: { type: String, trim: true, maxlength: 4000 },
    photos: {
      type: [{ type: String, trim: true }],
      validate: [(arr) => arr.length <= 6, 'A parcel can have at most 6 photos'],
    },
    financingAvailable: { type: Boolean, default: false },
    insured: { type: Boolean, default: false },
    waterAccess: { type: Boolean, default: false },

    // Plot rating shown on cards and the listing page (e.g. "A+", "A", "B-"). Set by
    // the GIS/actuarial scoring engine and reviewable by admins.
    score: { type: String, trim: true, maxlength: 4 },

    keyFacts: keyFactsSchema,
    titleVerification: titleVerificationSchema,
    productivityReport: productivityReportSchema,
    mapData: mapDataSchema,
    videoWalkthrough: videoWalkthroughSchema,

    // Tracks whether the internal (admin/GIS) enrichment pass — key facts, productivity
    // report, map, and video walkthrough — has been completed for this listing yet.
    enrichmentStatus: {
      type: String,
      enum: ['pending', 'enriched'],
      default: 'pending',
      index: true,
    },
    enrichedBy: { type: String, trim: true, maxlength: 120 },
    enrichedAt: Date,

    status: {
      type: String,
      enum: ['available', 'under_review', 'leased', 'unlisted'],
      default: 'available',
      index: true,
    },
  },
  { timestamps: true }
);

parcelSchema.index({ title: 'text', location: 'text', county: 'text', crop: 'text' });

module.exports = mongoose.model('Parcel', parcelSchema);
